CREATE TABLE user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE,
  pass VARCHAR(255) NOT NULL
) ENGINE = INNODB;

CREATE TABLE card (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  spaces_left_0 TINYINT NULL DEFAULT 5,
  spaces_left_1 TINYINT NULL DEFAULT 5,
  spaces_left_2 TINYINT NULL DEFAULT 5,
  user_id INT UNSIGNED NOT NULL
) ENGINE = INNODB;

CREATE TABLE space (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  idx TINYINT UNSIGNED NOT NULL,
  number TINYINT UNSIGNED NOT NULL,
  called BOOL NULL DEFAULT FALSE,
  card_id SMALLINT UNSIGNED NOT NULL
) ENGINE = INNODB;